name: 'Label PR'
description: 'Adds labels to the PR based on branch name and more'
author: 'Jarek Tkaczyk'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  labels:
    description: 'JSON object as STRING with labels mapping, eg. {"wip":"🚧 Do not merge", "hotfix":"💣 hotfix", "release":"🎁 release", "partial":"⚙️ Partial", "feature":"🎊 Feature"}'
    required: true
branding:
  icon: 'user-plus'
  color: 'green'
runs:
  using: 'node12'
  main: 'lib/main.js'
